import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello world. <br/>I am Nao.
        </h1>
      </main>

        <div className={styles.footer}>
        <a href={'/'}>
        Back to Top
        </a>
      </div>
    </div>
  )
}

export default About