import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/NowNewNao/NowNewNao" target={"_blank"}>My Website</a>
        </h1>


        <div className={styles.grid}>
          <a href="./about" className={styles.card}>
            <h2>About &rarr;</h2>
          </a>

          <a href="/tech" className={styles.card}>
            <h2>Tech &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/NowNewNao"
          target="_blank"
          rel="noopener noreferrer"
        >
          Contact
        </a>
      </footer>
    </div>
  )
}

export default Home
